sudo: required
services:
- docker

before_install:
- docker pull dpollet/texlive:pillar

script:
- docker run --tty --rm --volume $PWD:/work dpollet/texlive:pillar make pdfbook spiralbook

deploy:
- provider: bintray
  file: .bintray.json
  on:
    repo: SquareBracketAssociates/Booklet-uFFI
  skip_cleanup: true
  user: ducasse
  key:
    secure: RME2bdfkcE0dyXPa+e+9dPIHld+Kxq+nLuR+xKCFk507KSrDjCR9ysnXvNnFZpSwVXixJD7CClFV/1RFQB+G0AQW/wQLjepIRxENPj2S3R3hxZeCkRHwWbS5KSI13eXikQII9+tYMd6kw6OadRS70x0cKDwbw51DMWw5JZcBOPPFMJywVa+UvYG23p2dG0qKk3eBz/8GF8IjT3PtHXjq5JbSudocVS+u8aNE3OuojWlqC1i2Ghpl+YR0pEMn4qQ7mbisqY9XOTLw8IMFrANnWj9PxVC/Ivs1yceWrZOB4aPpAE2x2/rtNUS/LgxhGwE7GuDqUVnbeRlwibsEW6y4XvpEm2ZqBteEN3V+3kDfXZkqFuFVFugFnuwx9FyjjKfvdobCyGf3SdVb7n0NJVPvKBEOI2hXv/rqTR6NRDpyKuIwC8Zq4n6f833eBx+8iF0Q+KUKq5Oc+UiW6Ic/J1KM8q3G6RgCvphOeMoDhsMw3MVS3m5btwiWPIWzmOSH+9ECdCW59i6STtjj85gVl8sl24bRjeiHbOhZI2B/tqxcOGtuJGkVgO6NhEZEb/MmDMR7Jrvohw0Xh1EQs3HF4BNDnDw+iI715rYjPp/6o4fjEbdx/SAu8HbJyZIu2klGuLADpatD2KUwEQfc9rnDQriLIkcVsWxUSF2BK2CGLxfBL0s=
- provider: releases
  file: build/unified-ffi.pdf
  on:
    tags: true
  skip_cleanup: true
  api_key:
    secure: pRfu3fr35BzqQDi1ul0SubPSwO8zcyIidqLRZPz3XIrH4qoy1Zgnq785dmB7ziNQqH+VJyh7askSFY3JLxL0d4P0eUgj2ZDIOhJsUQQ/ihevOBWbxlMOoEPjQfzA11l8WrNCQ566KrcYiISRi7bCg698kPTWSRwOmmvqXOJe5zGkuUbVmMNUV2oxaNV4JC8kVyVWHYy0nNMLEX/hzRZRh1+8K34/ds+fZ7irLrbDWMbKGHCyuLCSqv+zJJdu99nWLTclrCxFzK4DEHaMlFiO7wkUpyQLwZ38EDnb3E7iv045jSqCx3XB+DMRG1Da2/9BIXl0mho5ELdEvfGVAbjI2no5FWd0H1cs4/banAePCFnM7ZscJBaPWgVajB7EzrcADJUoxpmU6+6n1aIC3CnjscfAHqSAKGv8CO/Jh+Uirc8ATRpSqa73f2Nnj9tRCqwCOnFOCEzu0w5l3Ppz2Qpif04P+QbebZehSVaBJ4W01R2i8Rac3IuZDhZVaek1X24HFxUOd/rvHpbhz8eeANdnsWCTkAm+0sD+iKsWKICRMxFZfCK/SPldAcjXZsOsEMTqfx7ZWyCc7GeesQWcmW+z3shziyQd9tdeArJWLwacly3hH3WeyuUD5JyPF9klvDBtHgTVajdU4yp+3oXsrtTmetnBz+RESxQGdLgZRlQBQog=
